FROM debian:buster-slim
ENV DEBIAN_FRONTEND=noninteractive
RUN \
  apt-get -y update && \
  apt-get install -y gcc gosu libcurl4-openssl-dev libsqlite3-dev ldc make && \
  apt-get clean && \
  rm -rf /var/cache/apt/archives/* /var/lib/apt/lists/*
RUN mkdir -p /onedrive/conf /onedrive/data
ADD . /usr/src/onedrive
RUN cd /usr/src/onedrive && \
    make DC=ldc2 install.noservice && \
    make clean
ADD docker/entrypoint.sh /entrypoint.sh
VOLUME ["/onedrive/conf"]
ENTRYPOINT ["/entrypoint.sh"]
