#!/bin/sh
# postinstall for onedrive
# (c) 2020 Norbert Preining

# try to restart running services
case $action in
  configure|reconfigure)
    restart_units="`systemctl list-units --no-legend --type=service --state=running 'onedrive*' | awk '{print$1}'`"
    if ! [ "x$restart_units" = "x" ] ; then
      echo -n "Restarting running Onedrive processes ... "
      for unit in `systemctl list-units --no-legend --type=service --state=running 'onedrive*' | awk '{print$1}'` ; do
        echo -n "$unit "
        systemctl restart "$unit"
      done
      echo "."
    fi
  ;;
esac



